# Generated by Django 5.0.6 on 2024-06-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign_reach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=10)),
                ('zip_total_people', models.IntegerField()),
                ('zip_audience_people', models.IntegerField()),
                ('zip_target_density', models.FloatField()),
                ('cumulative_reach', models.IntegerField()),
                ('target_density', models.FloatField()),
                ('cumulative_aud_reach', models.IntegerField()),
                ('cumulative_total_reach', models.IntegerField()),
                ('cumulative_pct_reach', models.FloatField()),
                ('cumulative_target_density', models.FloatField()),
            ],
        ),
    ]
