# Generated by Django 5.0.6 on 2024-06-13 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_reach', '0002_initial'),
    ]

    operations = [
    ]
