# Generated by Django 5.0.6 on 2024-06-13 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_reach', '0004_auto_20240613_0221'),
    ]

    operations = [
    ]
